FROM joshuar/gosu:latest

MAINTAINER Joshua Rich "joshua.rich@gmail.com"

# Environment variables for:
# - Kibana version
# - Kibana download URL
# - User to run Kibana as inside the container
# - UID to use for Kibana user
ARG KB_VERSION
ENV KB_HOME /opt/kibana
ENV PATH $KB_HOME/bin:$PATH

# Set up some custom labels for:
# - Kibana version
# - Dockerfile license
LABEL version=$KB_VERSION \
      license="Apache 2.0"

# Create an kibana user
RUN groupadd -r -g 900 kibana && \
	useradd -r -u 900 -d / -g kibana -s /sbin/nologin kibana

RUN dnf -y install libstdc++

# URL to download Kibana
ENV KB_URL https://artifacts.elastic.co/downloads/kibana/kibana-$KB_VERSION-linux-x86_64.tar.gz

# Download and install Kibana
RUN curl -s -L -o - $KB_URL | tar -C /opt -xz && \
	ln -s /opt/kibana-$KB_VERSION-linux-x86_64 $KB_HOME && \
	chown kibana:kibana $KB_HOME/optimize $KB_HOME/data

# Install plugins
RUN kibana-plugin install x-pack

# Set working directory
WORKDIR $KB_HOME

# Install entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set up entrypoint, forwarded ports and default command
ENTRYPOINT [ "/entrypoint.sh" ]
EXPOSE "5601/tcp"
CMD [ "kibana" ]
