FROM joshuar/java:latest

MAINTAINER Joshua Rich "joshua.rich@gmail.com"

ARG ES_VERSION
ENV ES_HOME /opt/elasticsearch
ENV ES_CONF_DIR /opt/elasticsearch/config
ENV ES_DATA_DIR /opt/elasticsearch/data
ENV ES_LOG_DIR /opt/elasticsearch/logs
ENV PATH $ES_HOME/bin:$PATH

# Performance Tweaks
RUN echo "elasticsearch - nofile 131070" >> /etc/security/limits.conf && \
    echo "elasticsearch - memlock unlimited" >> /etc/security/limits.conf && \
    echo vm.max_map_count=262144 > /etc/sysctl.d/max_map_count.conf
ENV MAX_OPEN_FILES=131070
ENV MAX_LOCKED_MEMORY=unlimited
ENV MAX_MAP_COUNT=262144

# Set up some custom labels for:
# - Elasticsearch version
# - Dockerfile license
LABEL version=$ES_VERSION \
      license="Apache 2.0"

# Create an elasticsearch user
RUN groupadd -r -g 900 elasticsearch && \
	useradd -r -u 900 -d / -g elasticsearch -s /sbin/nologin elasticsearch

# Set URL to download Elasticsearch
ENV ES_URL https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.tar.gz

# Download and install Elasticsearch into /opt/elasticsearch
RUN curl -s -L -o - $ES_URL | tar -C /opt -xz && \
	ln -s /opt/elasticsearch-$ES_VERSION $ES_HOME && \
	mkdir $ES_HOME/data $ES_HOME/logs $ES_HOME/config/scripts && \
	chown -R elasticsearch:elasticsearch $ES_HOME/data $ES_HOME/logs

# Install the commercial plugins.  These still need a license, which can be loaded
# after starting the container.
RUN plugin install elasticsearch/license/latest && \
    plugin install elasticsearch/marvel/latest && \
    plugin install elasticsearch/shield/latest && \
    plugin install elasticsearch/watcher/latest

# Volumes to mount on host
WORKDIR $ES_HOME

# Install entrypoint script
COPY entrypoint.sh /entrypoint.sh
COPY logging.yml $ES_HOME/config/logging.yml
COPY elasticsearch.yml $ES_HOME/config/elasticsearch.yml

RUN chmod +x /entrypoint.sh

# Set up entrypoint, forwarded ports and default command
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE "9200/tcp" "9300/tcp"
CMD ["elasticsearch"]
